server:
  port: 8080
  servlet:
    context-path: /im_bird_sys

spring:
  datasource:
    name: im_bird_sys
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.99.134.1:3306/im_bird?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    filters: stat
    initial-size: 2
    max-idle: 10
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-evict-runs-millis: 60000
    min-evictable-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
  #springmvc 视图解析器扫描前缀与后缀为指定名称的路径
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.im_bird_sys.controller: debug

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 39.99.134.18:22122







